---
abstract: 'Partially hash files, check if files are equal etc.'
author:
  - 'Copyright (C) 2011 by Daniel Friesel E<lt>derf@finalrewind.orgE<gt>'
build_requires:
  Test::Compile: 0
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Hashl
provides:
  App::Hashl:
    file: lib/App/Hashl.pm
    version: 1.00
requires:
  Digest::SHA: 0
  File::Copy: 0
  File::Find: 0
  Getopt::Long: 0
  IO::Handle: 0
  Storable: 0
  Time::Progress: 0
  perl: v5.10.0
version: 1.00
